services:
  django:
    build:
      context: ./django
      dockerfile: Dockerfile
    depends_on:
      - code-executor
    ports:
      - "8000:8000"
    env_file:
      - .env

  code-executor:
    build:
      context: ./executor
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    environment:
      FLASK_APP: "app.py"
    ports:
      - "5000:5000"