# Generated by Django 5.1 on 2024-10-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0002_problem_inputs_problem_outputs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='input',
            field=models.TextField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='output',
            field=models.TextField(max_length=4000),
        ),
    ]
