# Generated by Django 5.1 on 2024-11-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0003_alter_testcase_input_alter_testcase_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='inputs',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='outputs',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
