# Generated by Django 5.1 on 2024-11-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0004_alter_problem_inputs_alter_problem_outputs'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='input_signature',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='output_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
