# Generated by Django 5.1 on 2024-11-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0005_problem_input_signature_problem_output_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='input',
            field=models.JSONField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='output',
            field=models.JSONField(max_length=4000),
        ),
    ]
