# Generated by Django 5.1 on 2024-11-20 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0006_alter_testcase_input_alter_testcase_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='code',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='time_stamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
